---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.volumes.volumesCache.volumeCacheName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
